### ISSUE TITLE
Isn't this astroimutils now?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/astroimtools#24]
I thought @larrybradley renamed this to `astroimutils`? https://pypi.python.org/pypi/astroimutils

**Comment by larrybradley** [comment]
`astroimutils` was the first incarnation, but the name was changed to `astroimtools` (this repo).  I'll remove the PyPI `astroimutils`.

**Comment by pllim** [comment]
Okay, thanks for clarifying.
