### ISSUE TITLE
imcalc

### ISSUE THREAD

**Issue by larrybradley** [spacetelescope/astroimtools#8]
https://trello.com/c/IyQKUNi0

**Comment by hcferguson** [comment]
Use cases:

Create an rms map from a weight map:

 * imcalc weight_image, rms_image, calc="if im1 == 0 then some_large_number else 1/sqrt(im1)"

Create a mask (e.g. to use as a flag image for SExtractor)

 * imcalc rms_image, mask_image, calc="if im1 > some_value then 1 else 0"
